# Generated by Django 4.2.2 on 2023-06-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blockchain', models.CharField(max_length=50)),
                ('network', models.CharField(max_length=20)),
                ('wallet_id', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255, unique=True)),
                ('qr_b64', models.TextField(blank=True, null=True)),
                ('icon_url', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('nonactive', 'Non-Active')], max_length=10)),
            ],
            options={
                'db_table': 'payments_wallets',
            },
        ),
    ]
