# Generated by Django 4.2.2 on 2023-06-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
