# Generated by Django 4.2.2 on 2023-06-24 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recharges', '0002_transaction_expired_at_transaction_proof_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bill_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
